[manifest]

id = "leggettc18MM_FastText"
version = "1.0.0"
display_name = "Faster Text"
description =  """
Increases the speed of text and allows auto-advancing all text by holding B."""
short_description = "Speed up text."
authors = [ "leggettc18" ]
game_id = "mm"
minimum_recomp_version = "1.2.2"

dependencies = [
]

optional_dependencies = [
]

native_libraries = [
]

[inputs]
elf_path = "../../build/packages/FastText/mod.elf"
mod_filename = "leggettc18MM_FastText"
func_reference_syms_file = "../../Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "../../Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "../../Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]
additional_files = [ "thumb.png" ]

[[manifest.config_options]]
id = "text_scroll_mult"
name = "Text Scroll Multiplier"
description = "How much faster the text scrolls"
type = "Enum"
options = [ "1x", "2x", "4x", "8x", "16x" ]
default = "2x"

[[manifest.config_options]]
id = "auto_advance_text"
name = "Auto Advance"
description = "Toggles whether or not to auto-advance text boxes by holding the B button"
type = "Enum"
options = [ "On", "Off" ]
default = "On"
